# Generated by Django 5.0.14 on 2026-03-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='times_purchased',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
