services:
  - type: web
    name: ecommerce-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py seed_problem_statements && python manage.py seed_demo_data && python manage.py seed_full_catalog
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 3
    envVars:
      - key: DB_ENGINE
        value: sqlite
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PAYMENT_BACKEND
        value: mock

  - type: web
    name: ecommerce-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm ci && npx vite build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /api/*
        destination: https://ecommerce-backend.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html
