# Generated by Django 5.0.14 on 2026-03-21 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nces_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('locale', models.CharField(choices=[('city_large', 'City: Large'), ('city_midsize', 'City: Midsize'), ('city_small', 'City: Small'), ('suburban_large', 'Suburban: Large'), ('suburban_midsize', 'Suburban: Midsize'), ('suburban_small', 'Suburban: Small'), ('town_fringe', 'Town: Fringe'), ('town_distant', 'Town: Distant'), ('town_remote', 'Town: Remote'), ('rural_fringe', 'Rural: Fringe'), ('rural_distant', 'Rural: Distant'), ('rural_remote', 'Rural: Remote')], max_length=20)),
                ('enrollment', models.PositiveIntegerField(default=0)),
                ('frl_percentage', models.FloatField(default=0, help_text='Free/Reduced Lunch %')),
                ('el_percentage', models.FloatField(default=0, help_text='English Learner %')),
            ],
            options={
                'ordering': ['state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProblemStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='community.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('years_in_role', models.PositiveIntegerField(blank=True, null=True)),
                ('challenge_description', models.TextField(blank=True, help_text='Free-text description of current challenges')),
                ('challenge_embedding', models.JSONField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_profile', to=settings.AUTH_USER_MODEL)),
                ('problem_statements', models.ManyToManyField(blank=True, related_name='profiles', to='community.problemstatement')),
            ],
        ),
    ]
